### ISSUE TITLE
using the object 

### ISSUE THREAD

**Issue by ahmad681** [MikeHeiber/KMC_Lattice#77]
hey, if I want to have two different objects such two different atoms, interstitial and vacancies, how can I utilize the object class?

**Comment by MikeHeiber** [comment]
You will need to write child classes that extend the parent Object class. For example, in the Excimontec project, I made subclasses Exciton and Polaron and added the behavior associated with each separate entity using additional class attributes and methods. Definitely check out the KMC_Lattice_example and Excimontec projects to see examples of how to do this.
